site_name: Tantalim Documentation
pages:
- [index.md, Home]
- [client.md, Client]
- [server.md, Server]
- [pages.md, Pages]
- [contributing.md, Contributing]
- [about.md, About]
repo_url: https://github.com/tantalim/tantalim-docs/
theme: readthedocs
