site_name: Tantalim Documentation
site_url: http://docs.tantalim.com/

copyright: Copyright &copy; 2015, Tantalim.

repo_url: https://github.com/tantalim/tantalim-docs/

pages:
- ['index.md', 'Home']
- ['todo.md', 'General', 'Todo']
- ['getting-started.md', 'General', 'Getting Started']
- ['client/client.md', 'Client', 'Client']
- ['client/model-cursor.md', 'Client', 'ModelCursor']
- ['client/select.md', 'Client', 'SmartSelect']
- ['server.md', 'Backend', 'Server']
- ['pages.md', 'Structure', 'Pages']
- ['models.md', 'Structure', 'Models']
- ['bytecode.md', 'Structure', 'Bytecode']
- ['data.md', 'Structure', 'Data']
- ['tables.md', 'Structure', 'Tables']
- ['contributing.md', 'Other', 'Contributing']
- ['license.md', 'Other', 'License']
- ['about.md', 'Other', 'About']
theme: readthedocs
