site_name: Tantalim Documentation
site_url: http://docs.tantalim.com/

copyright: Copyright &copy; 2015, Tantalim.

repo_url: https://github.com/tantalim/tantalim-docs/

pages:
- ['index.md', 'Home']
- ['client.md', 'Client']
- ['server.md', 'Server']
- ['pages.md', 'Pages']
- ['select.md', 'SmartSelect']
- ['models.md', 'Models']
- ['contributing.md', 'Contributing']
- ['license.md', 'License']
- ['about.md', 'About']
theme: readthedocs
